# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_Basic_Spielscreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1177, 858)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frameHintergrund = QtWidgets.QFrame(self.centralwidget)
        self.frameHintergrund.setStyleSheet("QFrame {\n"
"    background-color: rgb(217, 198, 255);\n"
"}")
        self.frameHintergrund.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameHintergrund.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameHintergrund.setObjectName("frameHintergrund")
        self.gridLayout = QtWidgets.QGridLayout(self.frameHintergrund)
        self.gridLayout.setObjectName("gridLayout")
        self.frameFarbwahl = QtWidgets.QFrame(self.frameHintergrund)
        self.frameFarbwahl.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameFarbwahl.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameFarbwahl.setObjectName("frameFarbwahl")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frameFarbwahl)
        self.horizontalLayout_2.setContentsMargins(0, 1, 0, 4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButtonBlau = QtWidgets.QPushButton(self.frameFarbwahl)
        self.pushButtonBlau.setMinimumSize(QtCore.QSize(0, 26))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(14)
        self.pushButtonBlau.setFont(font)
        self.pushButtonBlau.setStyleSheet("QPushButton {\n"
"    background-color: rgb(125, 177, 255);\n"
"    border-top-left-radius : 5px;\n"
"    border-top-right-radius : 0px; \n"
"    border-bottom-left-radius : 0px; \n"
"    border-bottom-right-radius : 5px\n"
"}")
        self.pushButtonBlau.setObjectName("pushButtonBlau")
        self.horizontalLayout_2.addWidget(self.pushButtonBlau)
        self.pushButtonGruen = QtWidgets.QPushButton(self.frameFarbwahl)
        self.pushButtonGruen.setMinimumSize(QtCore.QSize(0, 26))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(14)
        self.pushButtonGruen.setFont(font)
        self.pushButtonGruen.setStyleSheet("QPushButton {\n"
"    background-color: rgb(169, 255, 149);\n"
"    border-top-left-radius : 5px;\n"
"    border-top-right-radius : 0px; \n"
"    border-bottom-left-radius : 0px; \n"
"    border-bottom-right-radius : 5px\n"
"}\n"
"")
        self.pushButtonGruen.setObjectName("pushButtonGruen")
        self.horizontalLayout_2.addWidget(self.pushButtonGruen)
        self.pushButtonGelb = QtWidgets.QPushButton(self.frameFarbwahl)
        self.pushButtonGelb.setMinimumSize(QtCore.QSize(0, 28))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(14)
        self.pushButtonGelb.setFont(font)
        self.pushButtonGelb.setStyleSheet("QPushButton {\n"
"    background-color: rgb(238, 226, 137);\n"
"    border-top-left-radius : 5px;\n"
"    border-top-right-radius : 0px; \n"
"    border-bottom-left-radius : 0px; \n"
"    border-bottom-right-radius : 5px\n"
"}\n"
"")
        self.pushButtonGelb.setObjectName("pushButtonGelb")
        self.horizontalLayout_2.addWidget(self.pushButtonGelb)
        self.pushButtoRot = QtWidgets.QPushButton(self.frameFarbwahl)
        self.pushButtoRot.setMinimumSize(QtCore.QSize(0, 28))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(14)
        self.pushButtoRot.setFont(font)
        self.pushButtoRot.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 165, 138);\n"
"    border-top-left-radius : 5px;\n"
"    border-top-right-radius : 0px; \n"
"    border-bottom-left-radius : 0px; \n"
"    border-bottom-right-radius : 5px\n"
"}\n"
"")
        self.pushButtoRot.setObjectName("pushButtoRot")
        self.horizontalLayout_2.addWidget(self.pushButtoRot)
        self.gridLayout.addWidget(self.frameFarbwahl, 5, 4, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 50, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout.addItem(spacerItem, 1, 4, 1, 1)
        self.frameLeftLast = QtWidgets.QFrame(self.frameHintergrund)
        self.frameLeftLast.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameLeftLast.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameLeftLast.setObjectName("frameLeftLast")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frameLeftLast)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 2, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(0, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem2, 1, 2, 1, 1)
        self.pushButtonLastCardSet = QtWidgets.QPushButton(self.frameLeftLast)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonLastCardSet.sizePolicy().hasHeightForWidth())
        self.pushButtonLastCardSet.setSizePolicy(sizePolicy)
        self.pushButtonLastCardSet.setMinimumSize(QtCore.QSize(30, 0))
        self.pushButtonLastCardSet.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setFamily("Georgia Pro Cond Semibold")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonLastCardSet.setFont(font)
        self.pushButtonLastCardSet.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pushButtonLastCardSet.setFlat(True)
        self.pushButtonLastCardSet.setObjectName("pushButtonLastCardSet")
        self.gridLayout_3.addWidget(self.pushButtonLastCardSet, 2, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(0, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem3, 3, 2, 1, 1)
        self.gridLayout.addWidget(self.frameLeftLast, 6, 1, 1, 1)
        self.frame_Stapel = QtWidgets.QFrame(self.frameHintergrund)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_Stapel.sizePolicy().hasHeightForWidth())
        self.frame_Stapel.setSizePolicy(sizePolicy)
        self.frame_Stapel.setMinimumSize(QtCore.QSize(400, 265))
        self.frame_Stapel.setBaseSize(QtCore.QSize(0, 270))
        self.frame_Stapel.setStyleSheet("")
        self.frame_Stapel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_Stapel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_Stapel.setObjectName("frame_Stapel")
        self.gridLayoutStapel = QtWidgets.QGridLayout(self.frame_Stapel)
        self.gridLayoutStapel.setContentsMargins(5, 5, 5, 6)
        self.gridLayoutStapel.setObjectName("gridLayoutStapel")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayoutStapel.addItem(spacerItem4, 1, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayoutStapel.addItem(spacerItem5, 1, 4, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayoutStapel.addItem(spacerItem6, 1, 2, 1, 1)
        self.pushButtonDraw_T = QtWidgets.QPushButton(self.frame_Stapel)
        self.pushButtonDraw_T.setMinimumSize(QtCore.QSize(145, 245))
        self.pushButtonDraw_T.setBaseSize(QtCore.QSize(145, 245))
        self.pushButtonDraw_T.setStyleSheet("QPushButton {\n"
"    background-color: rgb(72, 71, 72);\n"
"    border-radius: 15px;\n"
"    image: url(D:/Users/Wisdom/Documents/Weiteres/Projekte/UNO/Karten/default.png);\\n\n"
"}")
        self.pushButtonDraw_T.setText("")
        self.pushButtonDraw_T.setObjectName("pushButtonDraw_T")
        self.gridLayoutStapel.addWidget(self.pushButtonDraw_T, 1, 3, 1, 1)
        self.pushButton_Play_T = QtWidgets.QPushButton(self.frame_Stapel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Play_T.sizePolicy().hasHeightForWidth())
        self.pushButton_Play_T.setSizePolicy(sizePolicy)
        self.pushButton_Play_T.setMinimumSize(QtCore.QSize(145, 245))
        self.pushButton_Play_T.setSizeIncrement(QtCore.QSize(0, 0))
        self.pushButton_Play_T.setBaseSize(QtCore.QSize(145, 245))
        self.pushButton_Play_T.setStyleSheet("QPushButton {\n"
"    background-color: rgb(195, 190, 195);\n"
"    border-radius: 15px;\n"
"}")
        self.pushButton_Play_T.setText("")
        self.pushButton_Play_T.setObjectName("pushButton_Play_T")
        self.gridLayoutStapel.addWidget(self.pushButton_Play_T, 1, 1, 1, 1)
        self.gridLayout.addWidget(self.frame_Stapel, 3, 4, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(150, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem7, 3, 1, 1, 1)
        self.frameTop = QtWidgets.QFrame(self.frameHintergrund)
        self.frameTop.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameTop.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameTop.setObjectName("frameTop")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frameTop)
        self.horizontalLayout.setContentsMargins(10, 1, 10, 1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButtonUNO = QtWidgets.QPushButton(self.frameTop)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonUNO.sizePolicy().hasHeightForWidth())
        self.pushButtonUNO.setSizePolicy(sizePolicy)
        self.pushButtonUNO.setMinimumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.pushButtonUNO.setFont(font)
        self.pushButtonUNO.setStyleSheet("QPushButton {\n"
"    background-color:rgb(177, 90, 173);\n"
"    border-radius: 10px;\n"
"}")
        self.pushButtonUNO.setObjectName("pushButtonUNO")
        self.horizontalLayout.addWidget(self.pushButtonUNO)
        self.LabelSpielername = QtWidgets.QLabel(self.frameTop)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.LabelSpielername.setFont(font)
        self.LabelSpielername.setStyleSheet("")
        self.LabelSpielername.setAlignment(QtCore.Qt.AlignCenter)
        self.LabelSpielername.setObjectName("LabelSpielername")
        self.horizontalLayout.addWidget(self.LabelSpielername)
        self.gridLayout.addWidget(self.frameTop, 2, 4, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem8, 7, 4, 1, 1)
        self.framePassen = QtWidgets.QFrame(self.frameHintergrund)
        self.framePassen.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.framePassen.setFrameShadow(QtWidgets.QFrame.Raised)
        self.framePassen.setObjectName("framePassen")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.framePassen)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem9)
        self.pushButtonWeiter = QtWidgets.QPushButton(self.framePassen)
        self.pushButtonWeiter.setMinimumSize(QtCore.QSize(70, 32))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(14)
        self.pushButtonWeiter.setFont(font)
        self.pushButtonWeiter.setStyleSheet("QPushButton {\n"
"    background-color: rgb(177, 90, 173);\n"
"    border-radius: 5px;\n"
"}")
        self.pushButtonWeiter.setObjectName("pushButtonWeiter")
        self.horizontalLayout_3.addWidget(self.pushButtonWeiter)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem10)
        self.gridLayout.addWidget(self.framePassen, 4, 4, 1, 1)
        self.frameRightNext = QtWidgets.QFrame(self.frameHintergrund)
        self.frameRightNext.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameRightNext.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameRightNext.setObjectName("frameRightNext")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frameRightNext)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButtonNextCardSet = QtWidgets.QPushButton(self.frameRightNext)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonNextCardSet.sizePolicy().hasHeightForWidth())
        self.pushButtonNextCardSet.setSizePolicy(sizePolicy)
        self.pushButtonNextCardSet.setMinimumSize(QtCore.QSize(30, 0))
        self.pushButtonNextCardSet.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setFamily("Georgia Pro Cond Semibold")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonNextCardSet.setFont(font)
        self.pushButtonNextCardSet.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pushButtonNextCardSet.setFlat(True)
        self.pushButtonNextCardSet.setObjectName("pushButtonNextCardSet")
        self.gridLayout_2.addWidget(self.pushButtonNextCardSet, 2, 0, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(0, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem11, 3, 0, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(0, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem12, 1, 0, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem13, 2, 2, 1, 1)
        self.gridLayout.addWidget(self.frameRightNext, 6, 6, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(150, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem14, 3, 6, 1, 1)
        self.frame_Handkarten = QtWidgets.QFrame(self.frameHintergrund)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_Handkarten.sizePolicy().hasHeightForWidth())
        self.frame_Handkarten.setSizePolicy(sizePolicy)
        self.frame_Handkarten.setMinimumSize(QtCore.QSize(0, 261))
        self.frame_Handkarten.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.frame_Handkarten.setStyleSheet("QFrame {\n"
"    border: 5px solid  rgb(150, 129, 212);\n"
"}")
        self.frame_Handkarten.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_Handkarten.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_Handkarten.setObjectName("frame_Handkarten")
        self.gridLayout.addWidget(self.frame_Handkarten, 6, 4, 1, 1)
        self.verticalLayout.addWidget(self.frameHintergrund)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButtonBlau.setText(_translate("MainWindow", "Blau"))
        self.pushButtonGruen.setText(_translate("MainWindow", "Grün"))
        self.pushButtonGelb.setText(_translate("MainWindow", "Gelb"))
        self.pushButtoRot.setText(_translate("MainWindow", "Rot"))
        self.pushButtonLastCardSet.setText(_translate("MainWindow", "<"))
        self.pushButtonUNO.setText(_translate("MainWindow", "UNO"))
        self.LabelSpielername.setText(_translate("MainWindow", "hkjfh"))
        self.pushButtonWeiter.setText(_translate("MainWindow", "Passen"))
        self.pushButtonNextCardSet.setText(_translate("MainWindow", ">"))
