# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_game_over_screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MWinEnde(object):
    def setupUi(self, MWinEnde):
        MWinEnde.setObjectName("MWinEnde")
        MWinEnde.resize(1000, 650)
        self.centralwidget = QtWidgets.QWidget(MWinEnde)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("QFrame {\n"
"    background-color: rgb(217, 198, 255);\n"
"    border-radius: 15px;\n"
"}\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(0, 310, 981, 68))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButtonPlayAgain = QtWidgets.QPushButton(self.frame_2)
        self.pushButtonPlayAgain.setMinimumSize(QtCore.QSize(160, 50))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(20)
        self.pushButtonPlayAgain.setFont(font)
        self.pushButtonPlayAgain.setStyleSheet("QPushButton {\n"
"    background-color: rgb(225, 124, 200);\n"
"    border-radius: 25px\n"
"}")
        self.pushButtonPlayAgain.setObjectName("pushButtonPlayAgain")
        self.horizontalLayout.addWidget(self.pushButtonPlayAgain)
        spacerItem1 = QtWidgets.QSpacerItem(35, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.pushButtonMenu = QtWidgets.QPushButton(self.frame_2)
        self.pushButtonMenu.setMinimumSize(QtCore.QSize(160, 50))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Light")
        font.setPointSize(20)
        self.pushButtonMenu.setFont(font)
        self.pushButtonMenu.setStyleSheet("QPushButton {\n"
"    background-color: rgb(184, 101, 162);\n"
"    border-radius: 25px\n"
"}")
        self.pushButtonMenu.setObjectName("pushButtonMenu")
        self.horizontalLayout.addWidget(self.pushButtonMenu)
        spacerItem2 = QtWidgets.QSpacerItem(35, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.pushButtonQuit = QtWidgets.QPushButton(self.frame_2)
        self.pushButtonQuit.setMinimumSize(QtCore.QSize(160, 50))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Light")
        font.setPointSize(20)
        self.pushButtonQuit.setFont(font)
        self.pushButtonQuit.setStyleSheet("QPushButton {\n"
"    background-color: rgb(184, 101, 162);\n"
"    border-radius: 25px\n"
"}")
        self.pushButtonQuit.setObjectName("pushButtonQuit")
        self.horizontalLayout.addWidget(self.pushButtonQuit)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.labelSpielende = QtWidgets.QLabel(self.frame)
        self.labelSpielende.setGeometry(QtCore.QRect(0, 150, 1000, 51))
        self.labelSpielende.setMinimumSize(QtCore.QSize(1000, 50))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(28)
        self.labelSpielende.setFont(font)
        self.labelSpielende.setAlignment(QtCore.Qt.AlignCenter)
        self.labelSpielende.setObjectName("labelSpielende")
        self.labelGewinner = QtWidgets.QLabel(self.frame)
        self.labelGewinner.setGeometry(QtCore.QRect(0, 220, 1000, 50))
        self.labelGewinner.setMinimumSize(QtCore.QSize(1000, 50))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(24)
        self.labelGewinner.setFont(font)
        self.labelGewinner.setAlignment(QtCore.Qt.AlignCenter)
        self.labelGewinner.setObjectName("labelGewinner")
        self.verticalLayout.addWidget(self.frame)
        MWinEnde.setCentralWidget(self.centralwidget)

        self.retranslateUi(MWinEnde)
        QtCore.QMetaObject.connectSlotsByName(MWinEnde)

    def retranslateUi(self, MWinEnde):
        _translate = QtCore.QCoreApplication.translate
        MWinEnde.setWindowTitle(_translate("MWinEnde", "asdf"))
        self.pushButtonPlayAgain.setText(_translate("MWinEnde", "Noch Mal"))
        self.pushButtonMenu.setText(_translate("MWinEnde", "Start"))
        self.pushButtonQuit.setText(_translate("MWinEnde", "Beenden"))
        self.labelSpielende.setText(_translate("MWinEnde", "Spiel beendet"))
        self.labelGewinner.setText(_translate("MWinEnde", "<strong>Spieler</strong> hat gewonnen"))
