# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main_game_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1177, 858)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_background = QtWidgets.QFrame(self.centralwidget)
        self.frame_background.setStyleSheet("QFrame {\n"
"    background-color: rgb(217, 198, 255);\n"
"}")
        self.frame_background.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_background.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_background.setObjectName("frame_background")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_background)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_wild_color_choice = QtWidgets.QFrame(self.frame_background)
        self.frame_wild_color_choice.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_wild_color_choice.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_wild_color_choice.setObjectName("frame_wild_color_choice")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_wild_color_choice)
        self.horizontalLayout_2.setContentsMargins(0, 1, 0, 4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_wild_blue = QtWidgets.QPushButton(self.frame_wild_color_choice)
        self.pushButton_wild_blue.setMinimumSize(QtCore.QSize(0, 26))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(14)
        self.pushButton_wild_blue.setFont(font)
        self.pushButton_wild_blue.setStyleSheet("QPushButton {\n"
"    background-color: rgb(125, 177, 255);\n"
"    border-top-left-radius : 5px;\n"
"    border-top-right-radius : 0px; \n"
"    border-bottom-left-radius : 0px; \n"
"    border-bottom-right-radius : 5px\n"
"}")
        self.pushButton_wild_blue.setObjectName("pushButton_wild_blue")
        self.horizontalLayout_2.addWidget(self.pushButton_wild_blue)
        self.pushButton_wild_green = QtWidgets.QPushButton(self.frame_wild_color_choice)
        self.pushButton_wild_green.setMinimumSize(QtCore.QSize(0, 26))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(14)
        self.pushButton_wild_green.setFont(font)
        self.pushButton_wild_green.setStyleSheet("QPushButton {\n"
"    background-color: rgb(169, 255, 149);\n"
"    border-top-left-radius : 5px;\n"
"    border-top-right-radius : 0px; \n"
"    border-bottom-left-radius : 0px; \n"
"    border-bottom-right-radius : 5px\n"
"}\n"
"")
        self.pushButton_wild_green.setObjectName("pushButton_wild_green")
        self.horizontalLayout_2.addWidget(self.pushButton_wild_green)
        self.pushButton_wild_yellow = QtWidgets.QPushButton(self.frame_wild_color_choice)
        self.pushButton_wild_yellow.setMinimumSize(QtCore.QSize(0, 28))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(14)
        self.pushButton_wild_yellow.setFont(font)
        self.pushButton_wild_yellow.setStyleSheet("QPushButton {\n"
"    background-color: rgb(238, 226, 137);\n"
"    border-top-left-radius : 5px;\n"
"    border-top-right-radius : 0px; \n"
"    border-bottom-left-radius : 0px; \n"
"    border-bottom-right-radius : 5px\n"
"}\n"
"")
        self.pushButton_wild_yellow.setObjectName("pushButton_wild_yellow")
        self.horizontalLayout_2.addWidget(self.pushButton_wild_yellow)
        self.pushButton_wild_red = QtWidgets.QPushButton(self.frame_wild_color_choice)
        self.pushButton_wild_red.setMinimumSize(QtCore.QSize(0, 28))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(14)
        self.pushButton_wild_red.setFont(font)
        self.pushButton_wild_red.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 165, 138);\n"
"    border-top-left-radius : 5px;\n"
"    border-top-right-radius : 0px; \n"
"    border-bottom-left-radius : 0px; \n"
"    border-bottom-right-radius : 5px\n"
"}\n"
"")
        self.pushButton_wild_red.setObjectName("pushButton_wild_red")
        self.horizontalLayout_2.addWidget(self.pushButton_wild_red)
        self.gridLayout.addWidget(self.frame_wild_color_choice, 5, 4, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 50, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout.addItem(spacerItem, 1, 4, 1, 1)
        self.frame_left_last = QtWidgets.QFrame(self.frame_background)
        self.frame_left_last.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_left_last.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_left_last.setObjectName("frame_left_last")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_left_last)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 2, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(0, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem2, 1, 2, 1, 1)
        self.pushButton_last_card_set = QtWidgets.QPushButton(self.frame_left_last)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_last_card_set.sizePolicy().hasHeightForWidth())
        self.pushButton_last_card_set.setSizePolicy(sizePolicy)
        self.pushButton_last_card_set.setMinimumSize(QtCore.QSize(30, 0))
        self.pushButton_last_card_set.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setFamily("Georgia Pro Cond Semibold")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_last_card_set.setFont(font)
        self.pushButton_last_card_set.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pushButton_last_card_set.setFlat(True)
        self.pushButton_last_card_set.setObjectName("pushButton_last_card_set")
        self.gridLayout_3.addWidget(self.pushButton_last_card_set, 2, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(0, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem3, 3, 2, 1, 1)
        self.gridLayout.addWidget(self.frame_left_last, 6, 1, 1, 1)
        self.frame_talons = QtWidgets.QFrame(self.frame_background)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_talons.sizePolicy().hasHeightForWidth())
        self.frame_talons.setSizePolicy(sizePolicy)
        self.frame_talons.setMinimumSize(QtCore.QSize(400, 265))
        self.frame_talons.setBaseSize(QtCore.QSize(0, 270))
        self.frame_talons.setStyleSheet("")
        self.frame_talons.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_talons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_talons.setObjectName("frame_talons")
        self.gridLayoutStapel = QtWidgets.QGridLayout(self.frame_talons)
        self.gridLayoutStapel.setContentsMargins(5, 5, 5, 6)
        self.gridLayoutStapel.setObjectName("gridLayoutStapel")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayoutStapel.addItem(spacerItem4, 1, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayoutStapel.addItem(spacerItem5, 1, 4, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayoutStapel.addItem(spacerItem6, 1, 2, 1, 1)
        self.pushButton_Draw_Talon = QtWidgets.QPushButton(self.frame_talons)
        self.pushButton_Draw_Talon.setMinimumSize(QtCore.QSize(145, 245))
        self.pushButton_Draw_Talon.setBaseSize(QtCore.QSize(145, 245))
        self.pushButton_Draw_Talon.setStyleSheet("QPushButton {\n"
"    background-color: rgb(72, 71, 72);\n"
"    border-radius: 15px;\n"
"    image: url(D:/Users/Wisdom/Documents/Weiteres/Projekte/UNO/Karten/default.png);\\n\n"
"}")
        self.pushButton_Draw_Talon.setText("")
        self.pushButton_Draw_Talon.setObjectName("pushButton_Draw_Talon")
        self.gridLayoutStapel.addWidget(self.pushButton_Draw_Talon, 1, 3, 1, 1)
        self.pushButton_Play_Talon = QtWidgets.QPushButton(self.frame_talons)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Play_Talon.sizePolicy().hasHeightForWidth())
        self.pushButton_Play_Talon.setSizePolicy(sizePolicy)
        self.pushButton_Play_Talon.setMinimumSize(QtCore.QSize(145, 245))
        self.pushButton_Play_Talon.setSizeIncrement(QtCore.QSize(0, 0))
        self.pushButton_Play_Talon.setBaseSize(QtCore.QSize(145, 245))
        self.pushButton_Play_Talon.setStyleSheet("QPushButton {\n"
"    background-color: rgb(195, 190, 195);\n"
"    border-radius: 15px;\n"
"}")
        self.pushButton_Play_Talon.setText("")
        self.pushButton_Play_Talon.setObjectName("pushButton_Play_Talon")
        self.gridLayoutStapel.addWidget(self.pushButton_Play_Talon, 1, 1, 1, 1)
        self.gridLayout.addWidget(self.frame_talons, 3, 4, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(150, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem7, 3, 1, 1, 1)
        self.frame_uno_name = QtWidgets.QFrame(self.frame_background)
        self.frame_uno_name.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_uno_name.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_uno_name.setObjectName("frame_uno_name")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_uno_name)
        self.horizontalLayout.setContentsMargins(10, 1, 10, 1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_uno = QtWidgets.QPushButton(self.frame_uno_name)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_uno.sizePolicy().hasHeightForWidth())
        self.pushButton_uno.setSizePolicy(sizePolicy)
        self.pushButton_uno.setMinimumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_uno.setFont(font)
        self.pushButton_uno.setStyleSheet("QPushButton {\n"
"    background-color:rgb(177, 90, 173);\n"
"    border-radius: 10px;\n"
"}")
        self.pushButton_uno.setObjectName("pushButton_uno")
        self.horizontalLayout.addWidget(self.pushButton_uno)
        self.label_current_player = QtWidgets.QLabel(self.frame_uno_name)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_current_player.setFont(font)
        self.label_current_player.setStyleSheet("")
        self.label_current_player.setAlignment(QtCore.Qt.AlignCenter)
        self.label_current_player.setObjectName("label_current_player")
        self.horizontalLayout.addWidget(self.label_current_player)
        self.gridLayout.addWidget(self.frame_uno_name, 2, 4, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem8, 7, 4, 1, 1)
        self.frame_skip = QtWidgets.QFrame(self.frame_background)
        self.frame_skip.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_skip.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_skip.setObjectName("frame_skip")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_skip)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem9)
        self.pushButton_skip = QtWidgets.QPushButton(self.frame_skip)
        self.pushButton_skip.setMinimumSize(QtCore.QSize(70, 32))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(14)
        self.pushButton_skip.setFont(font)
        self.pushButton_skip.setStyleSheet("QPushButton {\n"
"    background-color: rgb(177, 90, 173);\n"
"    border-radius: 5px;\n"
"}")
        self.pushButton_skip.setObjectName("pushButton_skip")
        self.horizontalLayout_3.addWidget(self.pushButton_skip)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem10)
        self.gridLayout.addWidget(self.frame_skip, 4, 4, 1, 1)
        self.frame_right_next = QtWidgets.QFrame(self.frame_background)
        self.frame_right_next.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_right_next.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_right_next.setObjectName("frame_right_next")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_right_next)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_next_card_set = QtWidgets.QPushButton(self.frame_right_next)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_next_card_set.sizePolicy().hasHeightForWidth())
        self.pushButton_next_card_set.setSizePolicy(sizePolicy)
        self.pushButton_next_card_set.setMinimumSize(QtCore.QSize(30, 0))
        self.pushButton_next_card_set.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setFamily("Georgia Pro Cond Semibold")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_next_card_set.setFont(font)
        self.pushButton_next_card_set.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pushButton_next_card_set.setFlat(True)
        self.pushButton_next_card_set.setObjectName("pushButton_next_card_set")
        self.gridLayout_2.addWidget(self.pushButton_next_card_set, 2, 0, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(0, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem11, 3, 0, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(0, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem12, 1, 0, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem13, 2, 2, 1, 1)
        self.gridLayout.addWidget(self.frame_right_next, 6, 6, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(150, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem14, 3, 6, 1, 1)
        self.frame_player_hand = QtWidgets.QFrame(self.frame_background)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_player_hand.sizePolicy().hasHeightForWidth())
        self.frame_player_hand.setSizePolicy(sizePolicy)
        self.frame_player_hand.setMinimumSize(QtCore.QSize(0, 261))
        self.frame_player_hand.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.frame_player_hand.setStyleSheet("QFrame {\n"
"    border: 5px solid  rgb(150, 129, 212);\n"
"}")
        self.frame_player_hand.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_player_hand.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_player_hand.setObjectName("frame_player_hand")
        self.gridLayout.addWidget(self.frame_player_hand, 6, 4, 1, 1)
        self.verticalLayout.addWidget(self.frame_background)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_wild_blue.setText(_translate("MainWindow", "Blau"))
        self.pushButton_wild_green.setText(_translate("MainWindow", "Grün"))
        self.pushButton_wild_yellow.setText(_translate("MainWindow", "Gelb"))
        self.pushButton_wild_red.setText(_translate("MainWindow", "Rot"))
        self.pushButton_last_card_set.setText(_translate("MainWindow", "<"))
        self.pushButton_uno.setText(_translate("MainWindow", "UNO"))
        self.label_current_player.setText(_translate("MainWindow", "hkjfh"))
        self.pushButton_skip.setText(_translate("MainWindow", "Passen"))
        self.pushButton_next_card_set.setText(_translate("MainWindow", ">"))
